os: Windows Server 2012 R2
install:
 - ps: choco pack simutrans.nuspec
 - ps: choco pack pak64/simutrans-pak64.nuspec
 - ps: choco pack pak128/simutrans-pak128.nuspec
build: off
test: off
artifacts:
 # pushing all *.nupkg files in directory
 - path: '**\*.nupkg'
deploy:
 provider: NuGet
 server: http://chocolatey.org/api/v2/
 api_key:
   secure: ZQyhH/wCLJ4J+4Of15PiTKYuwXihZpKH++XbCNx+VnrDtp4R5LzeTNO4QoIIQM1X
 artifact: '*.nupkg'